#!/usr/bin/python
import os
from optparse import OptionParser
from soma_apps import pysynthsoma2
import time

if __name__ == "__main__":


    parser = OptionParser()
    parser.add_option("-i", "--ip", dest="ip",
                      help="ip address to send soma data to", default="127.0.0.1")
    
    (options, args) = parser.parse_args()
    
    runner = pysynthsoma2.default.ip(options.ip)

    runner.run()
    while(True) :
        time.sleep(1)
        s = runner.getStats()
        print s.eventcycles, s.eventcyclerate, s.datapackets, s.datapacketrate
    
    runner.shutdown()
    s = runner.getStats()

